[package]
name = "rtl_reshaper_rs"
version = "0.1.0"
authors = ["NightMachinary <rudiwillalwaysloveyou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arabic_reshaper = "0.2.0"
unic-bidi = "0.9.0"
